// Bu dosya sadece oyun listesini barındırır.
// Yeni oyun eklemek istersen buraya ekleyip kaydetmen yeterli.

const GAME_IDS = [
    { id: 730, name: "Counter-Strike 2", tags: ["Aksiyon", "Çok Oyunculu", "FPS", "Rekabetçi"] },
    { id: 570, name: "Dota 2", tags: ["Strateji", "Çok Oyunculu", "MOBA"] },
    { id: 440, name: "Team Fortress 2", tags: ["Aksiyon", "Çok Oyunculu", "Komik", "FPS"] },
    { id: 220, name: "Half-Life 2", tags: ["Aksiyon", "Bilim Kurgu", "Klasik", "Birinci Şahıs"] },
    { id: 620, name: "Portal 2", tags: ["Bulmaca", "Komedi", "Eşli", "Birinci Şahıs"] },
    { id: 550, name: "Left 4 Dead 2", tags: ["Aksiyon", "Korku", "Eşli", "Zombi"] },
    { id: 400, name: "Portal", tags: ["Bulmaca", "Bilim Kurgu", "Tek Oyunculu"] },
    { id: 10, name: "Counter-Strike", tags: ["Aksiyon", "FPS", "Klasik"] },
    { id: 12140, name: "Max Payne", tags: ["Aksiyon", "Klasik", "Hikaye Zengin"] },
    { id: 1659420, name: "UNCHARTED™: Legacy of Thieves Collection", tags: ["Macera", "Aksiyon", "Hikaye Zengin"] },
    { id: 813780, name: "Age of Empires II: Definitive Edition", tags: ["Strateji", "Tarihsel"] },
    { id: 254700, name: "Resident Evil 4 (2005)", tags: ["Korku", "Aksiyon", "Klasik"] },
    { id: 39140, name: "FINAL FANTASY VII", tags: ["RPG", "Klasik", "JRPG"] },
    { id: 7670, name: "BioShock™", tags: ["FPS", "Hikaye Zengin", "Atmosferik"] },
    { id: 814380, name: "Sekiro™: Shadows Die Twice", tags: ["Aksiyon", "Zor", "Souls-like"] },
    { id: 1546970, name: "Grand Theft Auto: San Andreas", tags: ["Aksiyon", "Açık Dünya", "Klasik"] },
    { id: 2131630, name: "METAL GEAR SOLID - Master Collection", tags: ["Gizlilik", "Aksiyon", "Klasik"] },
    { id: 730820, name: "The Curse of Monkey Island", tags: ["Macera", "Komedi", "Point & Click"] },
    { id: 1888930, name: "The Last of Us™ Part I", tags: ["Aksiyon", "Macera", "Hikaye Zengin", "Korku"] },
    { id: 1018960, name: "Call of Duty®: Modern Warfare®", tags: ["FPS", "Aksiyon", "Çok Oyunculu"] },
    { id: 1687950, name: "Persona 5 Royal", tags: ["RPG", "JRPG", "Anime"] },
    { id: 2124490, name: "Silent Hill 2", tags: ["Korku", "Psikolojik Korku", "Atmosferik"] },
    { id: 70, name: "Half-Life", tags: ["FPS", "Klasik", "Bilim Kurgu"] },
    { id: 13560, name: "Tom Clancy's Splinter Cell", tags: ["Gizlilik", "Aksiyon"] },
    { id: 205100, name: "Dishonored", tags: ["Gizlilik", "Aksiyon", "Steampunk"] },
    { id: 33230, name: "Assassin's Creed II", tags: ["Aksiyon", "Macera", "Tarihsel"] },
    { id: 200260, name: "Batman: Arkham City", tags: ["Aksiyon", "Macera", "Süper Kahraman"] },
    { id: 2050650, name: "Resident Evil 4", tags: ["Korku", "Aksiyon", "Remake"] },
    { id: 524220, name: "NieR:Automata™", tags: ["RPG", "Aksiyon", "Hikaye Zengin"] },
    { id: 32370, name: "STAR WARS™ - Knights of the Old Republic™", tags: ["RPG", "Bilim Kurgu", "Klasik"] },
    { id: 638230, name: "Journey", tags: ["Macera", "Bağımsız Yapım", "Rahatlatıcı"] },
    { id: 758330, name: "Shenmue I & II", tags: ["Macera", "Klasik", "Açık Dünya"] },
    { id: 1426210, name: "It Takes Two", tags: ["Eşli", "Macera", "Bulmaca"] },
    { id: 1593500, name: "God of War", tags: ["Aksiyon", "Macera", "Hikaye Zengin"] },
    { id: 632470, name: "Disco Elysium", tags: ["RPG", "Hikaye Zengin", "Dedektif"] },
    { id: 12210, name: "Grand Theft Auto IV", tags: ["Aksiyon", "Açık Dünya"] },
    { id: 1328670, name: "Mass Effect™ Legendary Edition", tags: ["RPG", "Bilim Kurgu", "Hikaye Zengin"] },
    { id: 1817070, name: "Marvel’s Spider-Man Remastered", tags: ["Aksiyon", "Açık Dünya", "Süper Kahraman"] },
    { id: 284050, name: "Sanitarium", tags: ["Korku", "Macera", "Klasik"] },
    { id: 271590, name: "GTA V", tags: ["Aksiyon", "Macera", "Araç Kullanma", "Açık Dünya"] },
    { id: 1174180, name: "Red Dead Redemption 2", tags: ["Macera", "Aksiyon", "Hikaye Zengin", "Atmosferik"] },
    { id: 1091500, name: "Cyberpunk 2077", tags: ["RPG", "Bilim Kurgu", "Aksiyon", "Açık Dünya"] },
    { id: 292030, name: "The Witcher 3", tags: ["RPG", "Macera", "Hikaye Zengin", "Fantastik"] },
    { id: 489830, name: "Skyrim Special Edition", tags: ["RPG", "Macera", "Fantastik", "Açık Dünya"] },
    { id: 377160, name: "Fallout 4", tags: ["RPG", "Kıyamet Sonrası", "Açık Dünya", "Nişancı"] },
    { id: 22380, name: "Fallout: New Vegas", tags: ["RPG", "Kıyamet Sonrası", "Açık Dünya", "Klasik"] },
    { id: 1151640, name: "Horizon Zero Dawn", tags: ["Macera", "Aksiyon", "Robot", "Açık Dünya"] },
    { id: 1245620, name: "Elden Ring", tags: ["RPG", "Zor", "Karanlık Fantazi", "Aksiyon"] },
    { id: 582010, name: "Monster Hunter: World", tags: ["Aksiyon", "RPG", "Eşli", "Canavar"] },
    { id: 239140, name: "Dying Light", tags: ["Aksiyon", "Zombi", "Parkur", "Açık Dünya"] },
    { id: 534380, name: "Dying Light 2", tags: ["Aksiyon", "Zombi", "Parkur", "RPG"] },
    { id: 356190, name: "Middle-earth: Shadow of War", tags: ["Aksiyon", "RPG", "Açık Dünya"] },
    { id: 242050, name: "Assassin's Creed IV Black Flag", tags: ["Aksiyon", "Macera", "Deniz", "Açık Dünya"] },
    { id: 582160, name: "Assassin's Creed Origins", tags: ["Aksiyon", "RPG", "Açık Dünya", "Tarihsel"] },
    { id: 812140, name: "Assassin's Creed Odyssey", tags: ["Aksiyon", "RPG", "Açık Dünya", "Tarihsel"] },
    { id: 2208920, name: "Assassin's Creed Valhalla", tags: ["Aksiyon", "RPG", "Açık Dünya", "Viking"] },
    { id: 289650, name: "Assassin's Creed Unity", tags: ["Aksiyon", "Macera", "Eşli"] },
    { id: 220240, name: "Far Cry 3", tags: ["Aksiyon", "FPS", "Açık Dünya"] },
    { id: 298110, name: "Far Cry 4", tags: ["Aksiyon", "FPS", "Açık Dünya"] },
    { id: 552520, name: "Far Cry 5", tags: ["Aksiyon", "FPS", "Açık Dünya"] },
    { id: 35140, name: "Batman: Arkham Asylum", tags: ["Aksiyon", "Macera", "Süper Kahraman"] },
    { id: 208650, name: "Batman: Arkham Knight", tags: ["Aksiyon", "Açık Dünya", "Süper Kahraman"] },
    { id: 870780, name: "Control", tags: ["Aksiyon", "Doğaüstü", "Hikaye Zengin"] },
    { id: 1332010, name: "Stray", tags: ["Macera", "Kedi", "Cyberpunk"] },
    { id: 990080, name: "Hogwarts Legacy", tags: ["RPG", "Açık Dünya", "Büyü", "Fantastik"] },
    { id: 1172470, name: "Apex Legends", tags: ["Aksiyon", "Çok Oyunculu", "Battle Royale"] },
    { id: 578080, name: "PUBG: BATTLEGROUNDS", tags: ["Aksiyon", "Hayatta Kalma - Korku", "Battle Royale"] },
    { id: 1938090, name: "Call of Duty®", tags: ["Aksiyon", "FPS", "Çok Oyunculu"] },
    { id: 359550, name: "Rainbow Six Siege", tags: ["Aksiyon", "FPS", "Rekabetçi"] },
    { id: 1085660, name: "Destiny 2", tags: ["Aksiyon", "MMO", "Bilim Kurgu"] },
    { id: 230410, name: "Warframe", tags: ["Aksiyon", "RPG", "Bilim Kurgu", "Eşli"] },
    { id: 218620, name: "Payday 2", tags: ["Aksiyon", "Eşli", "Soygun"] },
    { id: 1240440, name: "Halo Infinite", tags: ["Aksiyon", "FPS", "Bilim Kurgu"] },
    { id: 976730, name: "Halo: The Master Chief Collection", tags: ["Aksiyon", "FPS", "Bilim Kurgu"] },
    { id: 379720, name: "DOOM (2016)", tags: ["Aksiyon", "FPS", "Vahşet"] },
    { id: 782330, name: "DOOM Eternal", tags: ["Aksiyon", "FPS", "Vahşet"] },
    { id: 1238840, name: "Battlefield 1", tags: ["Aksiyon", "FPS", "Savaş"] },
    { id: 1517290, name: "Battlefield 2042", tags: ["Aksiyon", "FPS", "Savaş"] },
    { id: 1238810, name: "Battlefield V", tags: ["Aksiyon", "FPS", "Savaş"] },
    { id: 252950, name: "Rocket League", tags: ["Spor", "Çok Oyunculu", "Rekabetçi"] },
    { id: 222880, name: "Insurgency", tags: ["FPS", "Gerçekçi", "Taktiksel"] },
    { id: 581320, name: "Insurgency: Sandstorm", tags: ["FPS", "Gerçekçi", "Taktiksel"] },
    { id: 1144200, name: "Ready or Not", tags: ["FPS", "Taktiksel", "Eşli", "Polis"] },
    { id: 42700, name: "Call of Duty: Black Ops", tags: ["Aksiyon", "FPS"] },
    { id: 2000950, name: "Call of Duty: Modern Warfare", tags: ["Aksiyon", "FPS"] },
    { id: 739630, name: "Phasmophobia", tags: ["Korku", "Eşli", "VR"] },
    { id: 381210, name: "Dead by Daylight", tags: ["Korku", "Çok Oyunculu", "Hayatta Kalma - Korku"] },
    { id: 242760, name: "The Forest", tags: ["Korku", "Hayatta Kalma - Korku", "Macera"] },
    { id: 1325500, name: "Sons Of The Forest", tags: ["Korku", "Hayatta Kalma - Korku"] },
    { id: 412020, name: "Metro Exodus", tags: ["Aksiyon", "Korku", "Atmosferik"] },
    { id: 286690, name: "Metro 2033 Redux", tags: ["FPS", "Korku", "Kıyamet Sonrası"] },
    { id: 287390, name: "Metro: Last Light Redux", tags: ["FPS", "Korku", "Kıyamet Sonrası"] },
    { id: 214490, name: "Alien: Isolation", tags: ["Korku", "Bilim Kurgu", "Gizlilik"] },
    { id: 238320, name: "Outlast", tags: ["Korku", "Birinci Şahıs"] },
    { id: 414700, name: "Outlast 2", tags: ["Korku", "Birinci Şahıs"] },
    { id: 17470, name: "Dead Space", tags: ["Korku", "Bilim Kurgu", "Aksiyon"] },
    { id: 1693980, name: "Dead Space (Remake)", tags: ["Korku", "Bilim Kurgu", "Aksiyon"] },
    { id: 493520, name: "GTFO", tags: ["Korku", "Zor", "Eşli", "FPS"] },
    { id: 1966720, name: "Lethal Company", tags: ["Korku", "Komik", "Eşli"] },
    { id: 252490, name: "Rust", tags: ["Hayatta Kalma - Korku", "Çok Oyunculu", "Macera"] },
    { id: 892970, name: "Valheim", tags: ["Hayatta Kalma - Korku", "Viking", "Eşli"] },
    { id: 264710, name: "Subnautica", tags: ["Hayatta Kalma - Korku", "Macera", "Deniz"] },
    { id: 848450, name: "Subnautica: Below Zero", tags: ["Hayatta Kalma - Korku", "Macera", "Deniz"] },
    { id: 648800, name: "Raft", tags: ["Hayatta Kalma - Korku", "Macera", "Eşli"] },
    { id: 346110, name: "ARK: Survival Evolved", tags: ["Hayatta Kalma - Korku", "Dinozor"] },
    { id: 251570, name: "7 Days to Die", tags: ["Hayatta Kalma - Korku", "Zombi", "İnşa Etme"] },
    { id: 322330, name: "Don't Starve Together", tags: ["Hayatta Kalma - Korku", "2D", "Zor"] },
    { id: 305620, name: "The Long Dark", tags: ["Hayatta Kalma - Korku", "Atmosferik", "Kar"] },
    { id: 1623730, name: "Palworld", tags: ["Hayatta Kalma - Korku", "Canavar", "Açık Dünya"] },
    { id: 221100, name: "DayZ", tags: ["Hayatta Kalma - Korku", "Zombi", "Çok Oyunculu"] },
    { id: 108600, name: "Project Zomboid", tags: ["Hayatta Kalma - Korku", "Zombi", "Simülasyon"] },
    { id: 883710, name: "Resident Evil 2", tags: ["Korku", "Aksiyon", "Remake"] },
    { id: 952060, name: "Resident Evil 3", tags: ["Korku", "Aksiyon", "Remake"] },
    { id: 418370, name: "Resident Evil 7 Biohazard", tags: ["Korku", "Birinci Şahıs", "VR"] },
    { id: 1196590, name: "Resident Evil Village", tags: ["Korku", "Birinci Şahıs", "Aksiyon"] },
    { id: 227300, name: "Euro Truck Simulator 2", tags: ["Simülasyon", "Araç Kullanma", "Rahatlatıcı"] },
    { id: 270880, name: "American Truck Simulator", tags: ["Simülasyon", "Araç Kullanma"] },
    { id: 1222670, name: "The Sims 4", tags: ["Simülasyon", "Yaşam"] },
    { id: 255710, name: "Cities: Skylines", tags: ["Simülasyon", "Şehir Kurma", "Strateji"] },
    { id: 949230, name: "Cities: Skylines II", tags: ["Simülasyon", "Şehir Kurma"] },
    { id: 413150, name: "Stardew Valley", tags: ["Simülasyon", "RPG", "Piksel", "Rahatlatıcı"] },
    { id: 1063730, name: "New World", tags: ["MMO", "RPG"] },
    { id: 513710, name: "SCUM", tags: ["Simülasyon", "Hayatta Kalma - Korku"] },
    { id: 244850, name: "Space Engineers", tags: ["Simülasyon", "Uzay", "İnşa Etme"] },
    { id: 445220, name: "Avorion", tags: ["Simülasyon", "Uzay"] },
    { id: 1248130, name: "Farming Simulator 22", tags: ["Simülasyon", "Tarım"] },
    { id: 394360, name: "Hearts of Iron IV", tags: ["Strateji", "Tarihsel", "Savaş"] },
    { id: 236850, name: "Europa Universalis IV", tags: ["Strateji", "Tarihsel"] },
    { id: 1158310, name: "Crusader Kings III", tags: ["Strateji", "RPG", "Tarihsel"] },
    { id: 281990, name: "Stellaris", tags: ["Strateji", "Uzay", "Bilim Kurgu"] },
    { id: 1142710, name: "Total War: WARHAMMER III", tags: ["Strateji", "Fantastik"] },
    { id: 594570, name: "Total War: WARHAMMER II", tags: ["Strateji", "Fantastik"] },
    { id: 294100, name: "RimWorld", tags: ["Strateji", "Hayatta Kalma - Korku", "Simülasyon"] },
    { id: 427520, name: "Factorio", tags: ["Strateji", "İnşa Etme", "Otomasyon"] },
    { id: 526870, name: "Satisfactory", tags: ["Strateji", "İnşa Etme", "Birinci Şahıs"] },
    { id: 960090, name: "Bloons TD 6", tags: ["Strateji", "Kule Savunma"] },
    { id: 203290, name: "Company of Heroes 2", tags: ["Strateji", "Savaş"] },
    { id: 1466860, name: "Age of Empires IV", tags: ["Strateji", "Tarihsel"] },
    { id: 3590, name: "Plants vs. Zombies", tags: ["Strateji", "Klasik", "Kule Savunma"] },
    { id: 232090, name: "Killing Floor 2", tags: ["Aksiyon", "Zombi", "Eşli"] },
    { id: 268500, name: "XCOM 2", tags: ["Strateji", "Sıra Tabanlı", "Bilim Kurgu"] },
    { id: 466560, name: "Northgard", tags: ["Strateji", "Viking", "Şehir Kurma"] },
    { id: 613100, name: "House Flipper", tags: ["Simülasyon", "İnşa Etme", "Rahatlatıcı"] },
    { id: 1290000, name: "PowerWash Simulator", tags: ["Simülasyon", "Rahatlatıcı"] },
    { id: 105600, name: "Terraria", tags: ["Macera", "2D", "Bağımsız Yapım"] },
    { id: 1145360, name: "Hades", tags: ["Aksiyon Roguelike", "Bağımsız Yapım", "Aksiyon"] },
    { id: 646570, name: "Slay the Spire", tags: ["Strateji", "Kart Oyunu", "Bağımsız Yapım"] },
    { id: 632360, name: "Risk of Rain 2", tags: ["Aksiyon Roguelike", "3D", "Eşli"] },
    { id: 250900, name: "The Binding of Isaac: Rebirth", tags: ["Aksiyon Roguelike", "Korku"] },
    { id: 367520, name: "Hollow Knight", tags: ["Macera", "Metroidvania", "Zor"] },
    { id: 504230, name: "Celeste", tags: ["Platform", "Zor", "Bağımsız Yapım"] },
    { id: 268910, name: "Cuphead", tags: ["Aksiyon", "Zor", "2D"] },
    { id: 945360, name: "Among Us", tags: ["Çok Oyunculu", "Komik", "Bağımsız Yapım"] },
    { id: 1260320, name: "Party Animals", tags: ["Fizik Tabanlı", "Komik", "Çok Oyunculu"] },
    { id: 477160, name: "Human: Fall Flat", tags: ["Fizik Tabanlı", "Bulmaca", "Komik"] },
    { id: 4000, name: "Garry's Mod", tags: ["Fizik Tabanlı", "Komik", "Sandbox"] },
    { id: 431960, name: "Wallpaper Engine", tags: ["Yazılım", "Fizik Tabanlı"] },
    { id: 1794680, name: "Vampire Survivors", tags: ["Aksiyon Roguelike", "Basit Eğlence"] },
    { id: 1092790, name: "Inscryption", tags: ["Strateji", "Kart Oyunu", "Korku"] },
    { id: 247080, name: "Crypt of the NecroDancer", tags: ["Ritim", "Roguelike"] },
    { id: 962130, name: "Grounded", tags: ["Hayatta Kalma - Korku", "Macera"] },
    { id: 1293830, name: "Forza Horizon 4", tags: ["Yarış", "Araç Kullanma", "Açık Dünya"] },
    { id: 1551360, name: "Forza Horizon 5", tags: ["Yarış", "Araç Kullanma", "Açık Dünya"] },
    { id: 1080110, name: "F1® 22", tags: ["Yarış", "Simülasyon"] },
    { id: 2493840, name: "F1® 24", tags: ["Yarış", "Simülasyon"] },
    { id: 805550, name: "Assetto Corsa Competizione", tags: ["Yarış", "Simülasyon"] },
    { id: 244210, name: "Assetto Corsa", tags: ["Yarış", "Simülasyon"] },
    { id: 219990, name: "Grim Dawn", tags: ["RPG", "Hack and Slash"] },
    { id: 238960, name: "Path of Exile", tags: ["RPG", "Hack and Slash", "Oynaması Ücretsiz"] },
    { id: 49520, name: "Borderlands 2", tags: ["Aksiyon", "RPG", "FPS", "Komik"] },
    { id: 397540, name: "Borderlands 3", tags: ["Aksiyon", "RPG", "FPS", "Komik"] },
    { id: 1086940, name: "Baldur's Gate 3", tags: ["RPG", "Strateji"] },
    { id: 323190, name: "Frostpunk", tags: ["Strateji", "Şehir Kurma", "Hayatta Kalma - Korku"] },
    { id: 389730, name: "TEKKEN 7", tags: ["Dövüş", "Aksiyon", "Çok Oyunculu"] },
    { id: 1778820, name: "TEKKEN 8", tags: ["Dövüş", "Aksiyon", "Çok Oyunculu"] },
    { id: 1364780, name: "Street Fighter™ 6", tags: ["Dövüş", "Aksiyon", "Çok Oyunculu"] },
    { id: 976310, name: "Mortal Kombat 11", tags: ["Dövüş", "Vahşet", "Aksiyon"] },
    { id: 1978800, name: "Mortal Kombat 1", tags: ["Dövüş", "Vahşet", "Aksiyon"] },
    { id: 570940, name: "DARK SOULS™: REMASTERED", tags: ["RPG", "Zor", "Karanlık Fantazi"] },
    { id: 335300, name: "DARK SOULS™ II: Scholar of the First Sin", tags: ["RPG", "Zor"] },
    { id: 1172620, name: "Sea of Thieves", tags: ["Macera", "Aksiyon", "Korsan", "Eşli"] },
    { id: 2378620, name: "Anomaly Agent", tags: ["Aksiyon", "Platform", "Cyberpunk", "Türk Yapımı"] },
    { id: 261550, name: "Mount & Blade II: Bannerlord", tags: ["Strateji", "RPG", "Ortaçağ", "Savaş", "Türk Yapımı"] },
    { id: 48700, name: "Mount & Blade: Warband", tags: ["RPG", "Strateji", "Ortaçağ", "Klasik", "Türk Yapımı"] },
    { id: 3527290, name: "PEAK", tags: ["Macera", "Platform", "Zor", "Tırmanma"] },
    { id: 3949040, name: "RV There Yet?", tags: ["Macera", "Eşli", "Simülasyon", "Araç Kullanma"] },
    { id: 1808500, name: "ARC Raiders", tags: ["Aksiyon", "Nişancı", "Bilim Kurgu", "Eşli"] },
    { id: 2440510, name: "Forza Motorsport", tags: ["Yarış", "Simülasyon", "Spor"] },
    { id: 284160, name: "BeamNG.drive", tags: ["Simülasyon", "Araç Kullanma", "Fizik Tabanlı", "Sandbox"] },
];

module.exports = GAME_IDS;